version: '3.8'
name: academy
services:
  quotes:
    image: dirtyramirez/quotes
    container_name: quotes
    command: sleep 1000
    ports:
      - "8082:8082"
    networks:
      - default
  hero:
    image: dirtyramirez/hero
    container_name: hero
    ports:
      - "8081:8081"
    networks:
      - default

networks:
  myNetwork:
    driver: "bridge"